/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.ControlAdmin;
import Controlador.Validacion;
import Modelo.Administrador;
import java.awt.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;


/**
 *
 * @author joseo
 */
public class InternalRegistrarAdmin extends javax.swing.JInternalFrame {

    Validacion v = new Validacion();
    private boolean mostrandoContrasena = false;
    private boolean mostrandoContrasena2 = false;
    LocalDate fechaActual = LocalDate.now();
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy/MM/dd");
    String fechaString = fechaActual.format(formatter);
    /**
     * Creates new form InternalRegistrarAdmin
     */
    public InternalRegistrarAdmin() {
        initComponents();
        this.setSize(new Dimension(790,410));
        this.setTitle("Nuevo Usuario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        txtContra2 = new javax.swing.JPasswordField();
        txtContra1 = new javax.swing.JPasswordField();
        btnRegistrar = new javax.swing.JPanel();
        btnTextRegistrar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnMostrar1 = new javax.swing.JLabel();
        btnMostrar2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CREAR ADMINISTRADOR");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 300, 30));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("NOMBRE/S");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 204, 204));
        txtNombre.setText("Ingrese su nombre");
        txtNombre.setBorder(null);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 310, 20));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setAlignmentX(0.75F);
        jSeparator1.setOpaque(true);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 310, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("APELLIDOS");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        txtApellido.setBackground(new java.awt.Color(255, 255, 255));
        txtApellido.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(204, 204, 204));
        txtApellido.setText("Ingrese sus apellidos");
        txtApellido.setBorder(null);
        txtApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidoMousePressed(evt);
            }
        });
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApellidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 310, 20));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator5.setAlignmentX(0.75F);
        jSeparator5.setOpaque(true);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 310, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("CORREO");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        txtCorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(204, 204, 204));
        txtCorreo.setText("Ingrese su correo");
        txtCorreo.setBorder(null);
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCorreoKeyPressed(evt);
            }
        });
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 310, 20));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator6.setAlignmentX(0.75F);
        jSeparator6.setOpaque(true);
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 310, -1));

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("TELÉFONO");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        txtTelefono.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefono.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(204, 204, 204));
        txtTelefono.setText("Ingrese su teléfono");
        txtTelefono.setBorder(null);
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoMousePressed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 310, 20));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator7.setAlignmentX(0.75F);
        jSeparator7.setOpaque(true);
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 310, -1));

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("CONTRASEÑA");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator8.setAlignmentX(0.75F);
        jSeparator8.setOpaque(true);
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 310, -1));

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("CONFIRMAR CONTRASEÑA");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator9.setAlignmentX(0.75F);
        jSeparator9.setOpaque(true);
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 310, -1));

        txtContra2.setBackground(new java.awt.Color(255, 255, 255));
        txtContra2.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtContra2.setForeground(new java.awt.Color(204, 204, 204));
        txtContra2.setText("**********");
        txtContra2.setToolTipText("");
        txtContra2.setBorder(null);
        txtContra2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtContra2MousePressed(evt);
            }
        });
        txtContra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContra2ActionPerformed(evt);
            }
        });
        txtContra2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContra2KeyPressed(evt);
            }
        });
        jPanel1.add(txtContra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 310, 20));

        txtContra1.setBackground(new java.awt.Color(255, 255, 255));
        txtContra1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtContra1.setForeground(new java.awt.Color(204, 204, 204));
        txtContra1.setText("**********");
        txtContra1.setToolTipText("");
        txtContra1.setBorder(null);
        txtContra1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtContra1MousePressed(evt);
            }
        });
        txtContra1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContra1KeyPressed(evt);
            }
        });
        jPanel1.add(txtContra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 310, 20));

        btnRegistrar.setBackground(new java.awt.Color(162, 162, 162));

        btnTextRegistrar.setBackground(new java.awt.Color(162, 162, 162));
        btnTextRegistrar.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        btnTextRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        btnTextRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTextRegistrar.setText("REGISTRAR");
        btnTextRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnTextRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTextRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTextRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTextRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTextRegistrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnRegistrarLayout = new javax.swing.GroupLayout(btnRegistrar);
        btnRegistrar.setLayout(btnRegistrarLayout);
        btnRegistrarLayout.setHorizontalGroup(
            btnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTextRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnRegistrarLayout.setVerticalGroup(
            btnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTextRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 130, 40));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("(Mayuscula, Minuscula y Caracter especial)");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 200, -1));

        btnMostrar1.setBackground(new java.awt.Color(204, 204, 204));
        btnMostrar1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnMostrar1.setForeground(new java.awt.Color(0, 0, 0));
        btnMostrar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMostrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vista.png"))); // NOI18N
        btnMostrar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnMostrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrar1.setOpaque(true);
        btnMostrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMostrar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMostrar1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMostrar1MousePressed(evt);
            }
        });
        jPanel1.add(btnMostrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 40, 20));

        btnMostrar2.setBackground(new java.awt.Color(204, 204, 204));
        btnMostrar2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnMostrar2.setForeground(new java.awt.Color(0, 0, 0));
        btnMostrar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMostrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vista.png"))); // NOI18N
        btnMostrar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnMostrar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrar2.setOpaque(true);
        btnMostrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMostrar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMostrar2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMostrar2MousePressed(evt);
            }
        });
        jPanel1.add(btnMostrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 40, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Minimalist-Background_Wallpaper-for-PC (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        // TODO add your handling code here:
        if (txtNombre.getText().equals("Ingrese su nombre")) {
            txtNombre.setText("");
            txtNombre.setForeground(new Color(0, 0, 0));
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("Ingrese sus apellidos");
            txtApellido.setForeground(new Color(204, 204, 204));
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("Ingrese su correo");
            txtCorreo.setForeground(new Color(204, 204, 204));
        }
        if (txtTelefono.getText().isEmpty()) {
            txtTelefono.setText("Ingrese su teléfono");
            txtTelefono.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(txtContra1.getPassword()).isEmpty()) {
            txtContra1.setText("**********");
            txtContra1.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(txtContra2.getPassword()).isEmpty()) {
            txtContra2.setText("**********");
            txtContra2.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtApellido.setText("");
            txtApellido.setForeground(Color.black);
            if (txtNombre.getText().isEmpty()) {
                txtNombre.setText("Ingrese su nombre");
                txtNombre.setForeground(new Color(204, 204, 204));
            }
            txtApellido.requestFocus();
        }
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();

        boolean may = key >= 65 && key <= 90;
        boolean min = key >= 97 && key <= 122;
        boolean esp = key == 32;

        if (!(may || min || esp)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMousePressed
        // TODO add your handling code here:
        if (txtApellido.getText().equals("Ingrese sus apellidos")) {
            txtApellido.setText("");
            txtApellido.setForeground(new Color (0,0,0));
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("Ingrese su nombre");
            txtNombre.setForeground(new Color(204, 204, 204));
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("Ingrese su correo");
            txtCorreo.setForeground(new Color(204, 204, 204));
        }
        if (txtTelefono.getText().isEmpty()) {
            txtTelefono.setText("Ingrese su teléfono");
            txtTelefono.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(txtContra1.getPassword()).isEmpty()) {
            txtContra1.setText("**********");
            txtContra1.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(txtContra2.getPassword()).isEmpty()) {
            txtContra2.setText("**********");
            txtContra2.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_txtApellidoMousePressed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtCorreo.setText("");
            txtCorreo.setForeground(Color.black);
            if (txtApellido.getText().isEmpty()) {
                txtApellido.setText("Ingrese sus apellidos");
                txtApellido.setForeground(new Color(204, 204, 204));
            }
            txtCorreo.requestFocus();
        }
    }//GEN-LAST:event_txtApellidoKeyPressed

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();

        boolean may = key >= 65 && key <= 90;
        boolean min = key >= 97 && key <= 122;
        boolean esp = key == 32;

        if (!(may || min || esp)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        // TODO add your handling code here:
        if (txtCorreo.getText().equals("Ingrese su correo")) {
            txtCorreo.setText("");
            txtCorreo.setForeground(Color.black);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("Ingrese su nombre");
            txtNombre.setForeground(new Color(204, 204, 204));
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("Ingrese sus apellidos");
            txtApellido.setForeground(new Color(204, 204, 204));
        }
        if (txtTelefono.getText().isEmpty()) {
            txtTelefono.setText("Ingrese su teléfono");
            txtTelefono.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(txtContra1.getPassword()).isEmpty()) {
            txtContra1.setText("**********");
            txtContra1.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(txtContra2.getPassword()).isEmpty()) {
            txtContra2.setText("**********");
            txtContra2.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtCorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtTelefono.setText("");
            txtTelefono.setForeground(Color.black);
            if (txtCorreo.getText().isEmpty()) {
                txtCorreo.setText("Ingrese su correo");
                txtCorreo.setForeground(new Color(204, 204, 204));
            }
            txtTelefono.requestFocus();
        }
    }//GEN-LAST:event_txtCorreoKeyPressed

    private void txtTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMousePressed
        // TODO add your handling code here:
        if (txtTelefono.getText().equals("Ingrese su teléfono")) {
            txtTelefono.setText("");
            txtTelefono.setForeground(Color.black);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("Ingrese su nombre");
            txtNombre.setForeground(new Color(204, 204, 204));
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("Ingrese sus apellidos");
            txtApellido.setForeground(new Color(204, 204, 204));
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("Ingrese su correo");
            txtCorreo.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(txtContra1.getPassword()).isEmpty()) {
            txtContra1.setText("**********");
            txtContra1.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(txtContra2.getPassword()).isEmpty()) {
            txtContra2.setText("**********");
            txtContra2.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_txtTelefonoMousePressed

    private void txtTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtContra1.setText("");
            txtContra1.setForeground(Color.black);
            if (txtTelefono.getText().isEmpty()) {
                txtTelefono.setText("Ingrese su teléfono");
                txtTelefono.setForeground(new Color(204, 204, 204));
            }
            txtContra1.requestFocus();
        }
    }//GEN-LAST:event_txtTelefonoKeyPressed

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();

        boolean num = key >= 48 && key <= 57;

        if (!(num)) {
            evt.consume();
        }
        if (txtTelefono.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtContra2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContra2MousePressed
        // TODO add your handling code here:
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("Ingrese su nombre");
            txtNombre.setForeground(new Color(204, 204, 204));
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("Ingrese sus apellidos");
            txtApellido.setForeground(new Color(204, 204, 204));
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("Ingrese su correo");
            txtCorreo.setForeground(new Color(204, 204, 204));
        }
        if (txtTelefono.getText().isEmpty()) {
            txtTelefono.setText("Ingrese su teléfono");
            txtTelefono.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(txtContra2.getPassword()).equals("**********")) {
            txtContra2.setText("");
            txtContra2.setForeground(Color.black);
        }
        if (String.valueOf(txtContra1.getPassword()).isEmpty()) {
            txtContra1.setText("**********");
            txtContra1.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_txtContra2MousePressed

    private void txtContra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContra2ActionPerformed

    private void txtContra2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContra2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            Registrar();
        }
    }//GEN-LAST:event_txtContra2KeyPressed

    private void txtContra1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContra1MousePressed
        // TODO add your handling code here:
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("Ingrese su nombre");
            txtNombre.setForeground(new Color(204, 204, 204));
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("Ingrese sus apellidos");
            txtApellido.setForeground(new Color(204, 204, 204));
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("Ingrese su correo");
            txtCorreo.setForeground(new Color(204, 204, 204));
        }
        if (txtTelefono.getText().isEmpty()) {
            txtTelefono.setText("Ingrese su teléfono");
            txtTelefono.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(txtContra1.getPassword()).equals("**********")) {
            txtContra1.setText("");
            txtContra1.setForeground(Color.black);
        }
        if (String.valueOf(txtContra2.getPassword()).isEmpty()) {
            txtContra2.setText("**********");
            txtContra2.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_txtContra1MousePressed

    private void txtContra1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContra1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtContra2.setText("");
            txtContra2.setForeground(Color.black);
            if (txtContra1.getText().isEmpty()) {
                txtContra1.setText("**********");
                txtContra1.setForeground(new Color(204, 204, 204));
            }
            txtContra2.requestFocus();
        }
    }//GEN-LAST:event_txtContra1KeyPressed

    private void btnTextRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTextRegistrarMouseClicked
        Registrar();
    }//GEN-LAST:event_btnTextRegistrarMouseClicked

    private void btnTextRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTextRegistrarMouseEntered
        // TODO add your handling code here:
        btnRegistrar.setBackground(new Color(76, 76, 76));
        btnTextRegistrar.setForeground(Color.white);
    }//GEN-LAST:event_btnTextRegistrarMouseEntered

    private void btnTextRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTextRegistrarMouseExited
        // TODO add your handling code here:
        btnRegistrar.setBackground(new Color(162, 162, 162));
        btnTextRegistrar.setForeground(Color.black);
    }//GEN-LAST:event_btnTextRegistrarMouseExited

    private void btnMostrar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrar1MouseEntered
        // TODO add your handling code here:
        btnMostrar1.setBackground(new Color(76, 76, 76));
        btnMostrar1.setForeground(Color.white);
        btnMostrar1.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    }//GEN-LAST:event_btnMostrar1MouseEntered

    private void btnMostrar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrar1MouseExited
        // TODO add your handling code here:
        btnMostrar1.setBackground(new Color(204, 204, 204));
        btnMostrar1.setForeground(Color.black);
        btnMostrar1.setBorder(BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_btnMostrar1MouseExited

    private void btnMostrar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrar1MousePressed
        // TODO add your handling code here:
        if (mostrandoContrasena) {
            txtContra1.setEchoChar('*');
            mostrandoContrasena = false;
        } else {
            txtContra1.setEchoChar((char) 0);
            mostrandoContrasena = true;
        }
    }//GEN-LAST:event_btnMostrar1MousePressed

    private void btnMostrar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrar2MouseEntered
        // TODO add your handling code here:
        btnMostrar2.setBackground(new Color(76, 76, 76));
        btnMostrar2.setForeground(Color.white);
        btnMostrar2.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    }//GEN-LAST:event_btnMostrar2MouseEntered

    private void btnMostrar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrar2MouseExited
        // TODO add your handling code here:
        btnMostrar2.setBackground(new Color(204, 204, 204));
        btnMostrar2.setForeground(Color.black);
        btnMostrar2.setBorder(BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_btnMostrar2MouseExited

    private void btnMostrar2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrar2MousePressed
        // TODO add your handling code here:
        if (mostrandoContrasena2) {
            txtContra2.setEchoChar('*');
            mostrandoContrasena2 = false;
        } else {
            txtContra2.setEchoChar((char) 0);
            mostrandoContrasena2 = true;
        }
    }//GEN-LAST:event_btnMostrar2MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnMostrar1;
    private javax.swing.JLabel btnMostrar2;
    private javax.swing.JPanel btnRegistrar;
    private javax.swing.JLabel btnTextRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtContra1;
    private javax.swing.JPasswordField txtContra2;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    public void Registrar() {
        ControlAdmin Ca = new ControlAdmin();
        Administrador admin = new Administrador();
        if ((!txtNombre.getText().isEmpty() && !txtApellido.getText().isEmpty() && !txtCorreo.getText().isEmpty() && !txtTelefono.getText().isEmpty() && !txtContra1.getText().isEmpty() && !txtContra2.getText().isEmpty()) && (!txtNombre.getText().equals("Ingrese su nombre") || !txtApellido.getText().equals("Ingrese sus apellidos") || !txtCorreo.getText().equals("Ingrese su correo") || !txtTelefono.getText().equals("Ingrese su teléfono") || !String.valueOf(txtContra1.getPassword()).equals("**********") || !String.valueOf(txtContra2.getPassword()).equals("**********"))) {
            if (!v.validarCorreo(txtCorreo.getText())) {
                JOptionPane.showMessageDialog(null, "Correo invalido");
            } else if (!v.validarContra(String.valueOf(txtContra1.getPassword())) || !v.validarContra(String.valueOf(txtContra2.getPassword()))) {
                JOptionPane.showMessageDialog(null, "Contraseña invalida");
            } else {
                if (!Ca.ExisteAdmin(txtCorreo.getText().trim())) {
                    admin.setNombre(txtNombre.getText().trim());
                    admin.setApellido(txtApellido.getText().trim());
                    admin.setEmail(txtCorreo.getText().trim());
                    admin.setTelefono(txtTelefono.getText().trim());
                    admin.setFecha_registro(fechaString);
                    if (String.valueOf(txtContra1.getPassword()).equals(String.valueOf(txtContra2.getPassword()))) {
                        admin.setContrasena(String.valueOf(txtContra1.getPassword()));
                        if (Ca.RegistrarAdmin(admin)) {
                            JOptionPane.showMessageDialog(this, "Admin Registrado");
                            txtNombre.setText("Ingrese su nombre");
                            txtNombre.setForeground(new Color (204,204,204));
                            txtApellido.setText("Ingrese sus apellidos");
                            txtApellido.setForeground(new Color (204,204,204));
                            txtCorreo.setText("Ingrese su correo");
                            txtCorreo.setForeground(new Color (204,204,204));
                            txtTelefono.setText("Ingrese su teléfono");
                            txtTelefono.setForeground(new Color (204,204,204));
                            txtContra1.setText("**********");
                            txtContra1.setForeground(new Color (204,204,204));
                            txtContra2.setText("**********");;
                            txtContra2.setForeground(new Color (204,204,204));
                        } else {
                            JOptionPane.showMessageDialog(this, "El correo ya está registrado");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese sus datos");
        }
    }
}
