/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Conexion.Conexion;
import Controlador.ControlPagos;
import Controlador.EnviarCorreo;
import Controlador.PagosPDF;
import Modelo.Pagos;
import Modelo.Usuario;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author joseo
 */
public class InternalPagoServicios extends javax.swing.JInternalFrame {

    LocalDate fechaActual = LocalDate.now();
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    String fechaString = fechaActual.format(formatter);

    /**
     * Creates new form InternalPagoServicios
     */
    public InternalPagoServicios() {
        initComponents();
        this.setSize(new Dimension(790, 410));
        this.setTitle("Pagar Servicio");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MetodoPago = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtReferencia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtMonto = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtServicio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txtFecha = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JLabel();
        txtServicio1 = new javax.swing.JTextField();
        btnPagar = new javax.swing.JLabel();
        btnCredito = new javax.swing.JRadioButton();
        btnDebito = new javax.swing.JRadioButton();
        btnPagar1 = new javax.swing.JLabel();
        lblIdUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("PAGO DE SERVICIOS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 240, 30));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Referencia: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 105, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Servicio:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 165, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 200, 10));

        txtReferencia.setBackground(new java.awt.Color(255, 255, 255));
        txtReferencia.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtReferencia.setForeground(new java.awt.Color(0, 0, 0));
        txtReferencia.setBorder(null);
        txtReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReferenciaActionPerformed(evt);
            }
        });
        txtReferencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtReferenciaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtReferenciaKeyTyped(evt);
            }
        });
        jPanel1.add(txtReferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 198, 20));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Monto:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 225, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 200, 10));

        txtMonto.setEditable(false);
        txtMonto.setBackground(new java.awt.Color(255, 255, 255));
        txtMonto.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtMonto.setForeground(new java.awt.Color(0, 0, 0));
        txtMonto.setBorder(null);
        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });
        txtMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoKeyTyped(evt);
            }
        });
        jPanel1.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 198, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 200, 10));

        txtServicio.setBackground(new java.awt.Color(255, 255, 255));
        txtServicio.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtServicio.setForeground(new java.awt.Color(255, 255, 255));
        txtServicio.setBorder(null);
        txtServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServicioActionPerformed(evt);
            }
        });
        txtServicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtServicioKeyTyped(evt);
            }
        });
        jPanel1.add(txtServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 198, 20));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha de Vencimiento:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 305, -1, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 200, 10));

        txtFecha.setEditable(false);
        txtFecha.setBackground(new java.awt.Color(255, 255, 255));
        txtFecha.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(0, 0, 0));
        txtFecha.setBorder(null);
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        txtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaKeyTyped(evt);
            }
        });
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 198, 20));

        btnBuscar.setBackground(new java.awt.Color(162, 162, 162));
        btnBuscar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscar.setText("Buscar");
        btnBuscar.setOpaque(true);
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 100, 30));

        txtServicio1.setEditable(false);
        txtServicio1.setBackground(new java.awt.Color(255, 255, 255));
        txtServicio1.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtServicio1.setForeground(new java.awt.Color(0, 0, 0));
        txtServicio1.setBorder(null);
        txtServicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServicio1ActionPerformed(evt);
            }
        });
        txtServicio1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtServicio1KeyTyped(evt);
            }
        });
        jPanel1.add(txtServicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 198, 20));

        btnPagar.setBackground(new java.awt.Color(162, 162, 162));
        btnPagar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnPagar.setForeground(new java.awt.Color(0, 0, 0));
        btnPagar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPagar.setText("Pagar");
        btnPagar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPagar.setOpaque(true);
        btnPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPagarMouseClicked(evt);
            }
        });
        jPanel1.add(btnPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 100, 30));

        btnCredito.setBackground(new java.awt.Color(0, 0, 0));
        MetodoPago.add(btnCredito);
        btnCredito.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnCredito.setSelected(true);
        btnCredito.setText("T. de Crédito");
        jPanel1.add(btnCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 130, -1));

        btnDebito.setBackground(new java.awt.Color(0, 0, 0));
        MetodoPago.add(btnDebito);
        btnDebito.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnDebito.setText("T. de Débito");
        jPanel1.add(btnDebito, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 130, -1));

        btnPagar1.setBackground(new java.awt.Color(162, 162, 162));
        btnPagar1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnPagar1.setForeground(new java.awt.Color(0, 0, 0));
        btnPagar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPagar1.setText("Datos de la Tarjeta");
        btnPagar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPagar1.setOpaque(true);
        btnPagar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPagar1MouseClicked(evt);
            }
        });
        jPanel1.add(btnPagar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 130, 30));

        lblIdUser.setBackground(new java.awt.Color(255, 255, 255));
        lblIdUser.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblIdUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Minimalist-Background_Wallpaper-for-PC (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 390));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReferenciaActionPerformed

    private void txtReferenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReferenciaKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();

        boolean num = key >= 48 && key <= 57;

        if (!(num)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtReferenciaKeyTyped

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private void txtMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoKeyTyped

    private void txtServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServicioActionPerformed

    private void txtServicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtServicioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServicioKeyTyped

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtFechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaKeyTyped

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:

        if (!txtReferencia.getText().isEmpty()) {
            EnviarDatosConfig();
            EnviarDatosServicio();
        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void txtServicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServicio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServicio1ActionPerformed

    private void txtServicio1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtServicio1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServicio1KeyTyped

    private void btnPagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagarMouseClicked
        // TODO add your handling code here:

        RegistrarPago();
    }//GEN-LAST:event_btnPagarMouseClicked

    private void btnPagar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagar1MouseClicked
        // TODO add your handling code here:
        if (btnCredito.isSelected() || btnDebito.isSelected()) {
            MetodoPago mp = new MetodoPago();
            VistaUser.JDP_Menu.add(mp);
            mp.setVisible(true);
        }
    }//GEN-LAST:event_btnPagar1MouseClicked

    private void txtReferenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReferenciaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            EnviarDatosConfig();
            EnviarDatosServicio();
        }
    }//GEN-LAST:event_txtReferenciaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup MetodoPago;
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JRadioButton btnCredito;
    private javax.swing.JRadioButton btnDebito;
    private javax.swing.JLabel btnPagar;
    private javax.swing.JLabel btnPagar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblIdUser;
    public static javax.swing.JTextField txtFecha;
    public static javax.swing.JTextField txtMonto;
    public static javax.swing.JTextField txtReferencia;
    public static javax.swing.JTextField txtServicio;
    public static javax.swing.JTextField txtServicio1;
    // End of variables declaration//GEN-END:variables

    private void EnviarDatosConfig() {
        try {
            Connection cn = Conexion.establecerConexion();
            PreparedStatement pst = cn.prepareStatement("select * from configuracionvencimientos where id_configuracion = '" + txtReferencia.getText() + "'");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txtServicio.setText(rs.getString("id_servicio"));
                txtFecha.setText(rs.getString("fecha_vencimiento"));
                txtMonto.setText(rs.getString("monto"));

            }
        } catch (SQLException e) {
            System.out.println("Error al seleccionar" + e);
        }
    }

    private void EnviarDatosServicio() {
        try {
            Connection cn = Conexion.establecerConexion();
            PreparedStatement pst = cn.prepareStatement("select nombre from servicios where id_servicio = '" + txtServicio.getText() + "'");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txtServicio1.setText(rs.getString("nombre"));
            }
        } catch (SQLException e) {
            System.out.println("Error al seleccionar" + e);
        }
    }
    private String EnviarEmail() {
        String correo = "";
        try {
            Connection cn = Conexion.establecerConexion();
            PreparedStatement pst = cn.prepareStatement("select email from usuarios where id_usuario = '" + 8 + "'");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                jLabel7.setText(rs.getString("email"));
                return correo = jLabel7.getText();
            }
        } catch (SQLException e) {
            System.out.println("Error al seleccionar" + e);
        }
        return correo;
    }

    public void RegistrarPago() {
        ControlPagos Cp = new ControlPagos();
        Pagos pago = new Pagos();
        EnviarCorreo eC = new EnviarCorreo();
        Usuario u = new Usuario();

        pago.setId_usuario(8);
        pago.setId_servicio(Integer.parseInt(txtServicio.getText().trim()));
        pago.setMonto(txtMonto.getText().trim());
        pago.setFecha_pago(fechaString);
        pago.setFecha_vencimiento(txtFecha.getText());
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        try {
            LocalDate fechaP = LocalDate.parse(fechaString, formato);
            LocalDate fechaV = LocalDate.parse(txtFecha.getText(), formato);

            if (fechaV.isBefore(fechaP)) {
                JOptionPane.showMessageDialog(null, "La fecha de límite de pago ya pasó");
            } else {
                if (Cp.RegistrarPago(pago)) {
                    JOptionPane.showMessageDialog(this, "Pago Registrado");
                    PagosPDF pdf = new PagosPDF();
                    pdf.DatosUsuario(8);
                    pdf.GenerarPDF();
                    txtReferencia.setText("");
                    txtServicio1.setText("");
                    txtMonto.setText("");
                    txtFecha.setText("");
                    eC.EnviarEmail(EnviarEmail(), "Factura de Pago de Servicios", "", pdf.Ruta());

                }
            }

        } catch (DateTimeParseException e) {
            // Manejo de error en caso de formato incorrecto
            System.out.println("Error al convertir la fecha: " + e.getMessage());
        }

    }
}
